version: "3"
services:
  #mysql:
    #image: mysql:8.0.23
    #command: --default-authentication-plugin=mysql_native_password
    # volumes:
    # - "./mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
  backend:
    build: .
    volumes:
      - ".:/backend"
    ports:
      - "3000:3000"
    tty: true
    #depends_on:
      #- mysql
